# Loading Data

```{r}
setwd("/Users/lucasquemelli/Documents/repos/telecom_customer_churn")
#source ("/Users/lucasquemelli/Documents/repos/telecom_customer_churn/data_ingestion.R")
#source ("/Users/lucasquemelli/Documents/repos/telecom_customer_churn/exploratory_data_analysis.R")
source ("/Users/lucasquemelli/Documents/repos/telecom_customer_churn//pre_processing.R")

set.seed(007)
churn_data_raw = read.csv("/Users/lucasquemelli/Documents/repos/telecom_customer_churn/data/churn.csv")
```

```{r}
churn_data_raw
```

```{r}
View(churn_data_raw)
```

```{r}
####### EDA #######
### Selecting Numerical variables to visualize
num_variables <- c("Churn", "MonthlyCharges", "tenure", "TotalCharges")
num_var_data  <-  churn_data_raw[num_variables]

### Bi-variate analysis  

#Visualize the numerical data
plot_num_var(num_var_data)
```

```{r}
#Visualize the categorical data
cat_var_data=churn_data_raw[,sapply(churn_data_raw,is.character) ]
plot_cat_var(cat_var_data)
```

# Data Pre-processing 

-   In this section, we removed the missing values and split the data.

```{r}
####### Data Pre-Processing #######
missing_data_snapshot(churn_data_raw)
x<-preprocess_data(churn_data_raw)
```

Since the percentage of missing values is very low, we removed all of them.

```{r}
# Percentage of missing values
100*11/7032
```
